// project\src\app\layout.tsx 파일
import Navbar from "./Navbar";
import "../../styles/reset.css";
import RecoilRootWrapper from "./RecoilWrapper";


interface LayoutProps {
  children: React.ReactNode;
}

export const metadata = {
  title: "MonoLetter",
  description: "Generated by 앵",
  icons: {
    icon: "/icon.png",
  },
};

export default function Layout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <RecoilRootWrapper>{children}</RecoilRootWrapper>
      </body>
    </html>
  );
}
